[workspace]
resolver = "3"
members = ["blur_plugin", "image_processor", "mirror_plugin"]

[workspace.dependencies]
libloading = "0.9"
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"