[package]
name = "image_processor"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
thiserror = "2"
clap = { version = "4", features = ["derive"] }
image = { version = "0.25" }
libc = { workspace = true }
libloading = { workspace = true }